# Generated by Django 2.2 on 2021-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=10000)),
                ('number', models.IntegerField()),
                ('animalname', models.TextField(max_length=10000)),
                ('whatsapp', models.TextField(max_length=255)),
                ('instagram', models.TextField(max_length=255)),
                ('facebook', models.TextField(max_length=255)),
            ],
        ),
    ]
